Header:
  Title:  "Apex Cougar Club"
  SubTitle:  "Supporting Apex HS Athletics"
  AppName:  "Apex Cougar Club Mobile App"

School:
  Name:  "Apex High School"
  Conference:  "SWAC4A"
  Classification:  "4A"
  Address:  "7600 Roberts Rd."
  City:  "Cary"
  State:  "North Carolina"
  ZipCode:  "27519"
  Phone:  "+1-919-387-2208"
  WebSite:  "http://www.apexhigh.com"
  Twitter:  "@ApexHighSchool"
  Principal:  "Dr. Diann Kearney"
  PrincipalEmail:  "dkearney@wcpss.net"
  AthleticDirector:  "Del Philips"
  AthleticDirectorEmail:  "wphillips@wcpss.net"
  HomeVenueId:  1
  SchoolYear:  "2017-2018"

GoogleMaps:
  Enabled:  "No"

Twitter:
  Enabled:  "Yes"
  Username: "apexcougarclub"
  ConsumerKey: "YOUR_CONSUMER_KEY"
  ConsumerSecret: "YOUR_CONSUMER_SECRET"
  AccessToken: "YOUR_ACCESS_TOKEN"
  AccessTokenSecret: "YOUR_ACCESS_SECRET"

AppSettings:
  AutoTweetResults: On
  AutoTweetScheduleUpdates: On
  BannerAds: On
  SplashAds: On
  OfflineMode: Off
  SignUpGenius: On
